"""
MITRE ATT&CK Navigator layer export.

Turns Ganglion's detection coverage into a Navigator *layer* file — the exact
JSON format the official ATT&CK Navigator (https://mitre-attack.github.io/attack-navigator/)
consumes. A blue-teamer can take the output of this module, click "Open Existing
Layer → Upload from local", and instantly *see* Ganglion's coverage painted on
the real ATT&CK matrix — the tool every SOC already uses.

Two views:
  * coverage layer  — every technique Ganglion *can* detect (from its mapping
    table), so reviewers see the breadth of built-in detection content.
  * live layer      — only techniques actually *observed this session*, scored
    by how many times they fired, so an IR lead sees the current engagement.

No third-party libraries: a Navigator layer is just JSON.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Dict, Iterable, List, Optional

try:
    from mitre_attack import TECHNIQUES, TACTICS, _EVENT_MAP as EVENT_TECHNIQUE_MAP
except ImportError:  # when imported as common.attack_navigator
    from common.mitre_attack import TECHNIQUES, TACTICS, _EVENT_MAP as EVENT_TECHNIQUE_MAP

LAYER_VERSION = "4.5"
NAVIGATOR_VERSION = "4.9.1"
ATTACK_VERSION = "14"

# green (covered) → red (hot/observed)
_GRADIENT = ["#8ec843", "#ffe766", "#ff6b6b"]


def _all_detectable_technique_ids() -> List[str]:
    ids = set()
    for tids in EVENT_TECHNIQUE_MAP.values():
        ids.update(tids)
    # keep only those we have full metadata for
    return sorted(t for t in ids if t in TECHNIQUES)


def _technique_entry(tid: str, score: int, comment: str = "") -> dict:
    return {
        "techniqueID": tid,
        "score": score,
        "comment": comment,
        "enabled": True,
        "metadata": [],
        "showSubtechniques": "." in tid,
    }


def build_layer(name: str, description: str,
                technique_scores: Dict[str, int],
                comments: Optional[Dict[str, str]] = None) -> dict:
    """Assemble a valid ATT&CK Navigator layer from {technique_id: score}."""
    comments = comments or {}
    scores = [s for s in technique_scores.values() if s > 0] or [1]
    techniques = [
        _technique_entry(tid, score, comments.get(tid, ""))
        for tid, score in sorted(technique_scores.items())
        if tid in TECHNIQUES
    ]
    return {
        "name": name,
        "versions": {"attack": ATTACK_VERSION, "navigator": NAVIGATOR_VERSION,
                     "layer": LAYER_VERSION},
        "domain": "enterprise-attack",
        "description": description,
        "created": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "techniques": techniques,
        "gradient": {"colors": _GRADIENT, "minValue": 0,
                     "maxValue": max(scores)},
        "legendItems": [
            {"label": "detection content available", "color": _GRADIENT[0]},
            {"label": "observed this session", "color": _GRADIENT[2]},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#205b70",
        "selectTechniquesAcrossTactics": True,
        "sorting": 3,
    }


def coverage_layer() -> dict:
    """Every technique Ganglion ships detection content for (score = 1)."""
    scores = {tid: 1 for tid in _all_detectable_technique_ids()}
    comments = {tid: f"{TECHNIQUES[tid].name} — built-in detection"
                for tid in scores}
    return build_layer(
        "Ganglion-OOB — Detection Coverage",
        "Techniques Ganglion-OOB can detect out of the box (deterministic, no ML). "
        "Generated by common/attack_navigator.py.",
        scores, comments)


def live_layer(technique_counts: Dict[str, int]) -> dict:
    """Techniques observed this session, scored by observation count."""
    scores = {tid: int(c) for tid, c in technique_counts.items() if tid in TECHNIQUES}
    comments = {tid: f"{TECHNIQUES[tid].name} — observed {scores[tid]}x this session"
                for tid in scores}
    if not scores:
        scores = {}  # empty but valid
    return build_layer(
        "Ganglion-OOB — Live Engagement",
        "Techniques actually observed by Ganglion-OOB this session, scored by "
        "observation frequency. Load into the ATT&CK Navigator to see the live "
        "kill chain on the real matrix.",
        scores, comments)


def write_layer(layer: dict, path: str) -> str:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(layer, fh, indent=2)
    return path


if __name__ == "__main__":
    import argparse, sys
    ap = argparse.ArgumentParser(description="Export an ATT&CK Navigator layer")
    ap.add_argument("--mode", choices=["coverage", "live"], default="coverage")
    ap.add_argument("--out", default="ganglion_attack_layer.json")
    args = ap.parse_args()
    layer = coverage_layer() if args.mode == "coverage" else live_layer({})
    write_layer(layer, args.out)
    n = len(layer["techniques"])
    print(f"Wrote {args.mode} layer with {n} techniques -> {args.out}")
    print("Load it at https://mitre-attack.github.io/attack-navigator/ "
          "(Open Existing Layer -> Upload from local)")
